# Generated by Django 4.2.4 on 2023-10-28 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="esp",
            old_name="timer",
            new_name="time",
        ),
    ]
