# Generated by Django 4.2.6 on 2023-10-28 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timer", "0002_rename_timer_esp_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="esp",
            old_name="time",
            new_name="timer",
        ),
    ]
